version: '2'

services:

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - .:/app/
    depends_on:
      - db
    working_dir: /app
    ports:
      - 80:8080
    environment:
      DATABASE_URL: db:5432
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    command: python3 flask_app.py

  db:
    image: postgres:10
    volumes:
      - ./docker/db/data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: otus_db