version: '2'

services:

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - .:/app/
    depends_on:
      - db
    ports:
      - 80:8080
    environment:
      DATABASE_URL: postgresql://admin:12345678@db/otus_db
    command: python3 flask_app.py

  db:
    image: postgres:10
    volumes:
      - ./docker/db/data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: otus_db