"""empty message

Revision ID: 465fd0db4555
Revises: f4f11cfb66d9
Create Date: 2018-07-08 23:44:36.154636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465fd0db4555'
down_revision = 'f4f11cfb66d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_table('user')
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_index(op.f('ix_product_params'), 'product', ['params'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_params'), table_name='product')
    op.drop_constraint(None, 'category', type_='unique')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('role', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
