"""empty message

Revision ID: deecc22de208
Revises: 465fd0db4555
Create Date: 2018-07-09 00:05:56.373853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deecc22de208'
down_revision = '465fd0db4555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=True)
    op.drop_index('ix_product_name', table_name='product')
    op.drop_column('product', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_product_name', 'product', ['name'], unique=True)
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.drop_column('product', 'title')
    # ### end Alembic commands ###
